[package]
name = "ntfy-windows-client"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "A lightweight native Windows client for ntfy"
license = "MIT"
repository = "https://github.com/manilka-gl/ntfy-windows-client"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slint = { version = "=1.17.1", default-features = false, features = [
    "std",
    "backend-winit",
    "renderer-software",
    "compat-1-2",
] }
ureq = { version = "2.12.1", default-features = false, features = ["tls"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = [
    "Data_Xml_Dom",
    "UI_Notifications",
] }

[build-dependencies]
slint-build = "=1.17.1"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"

[lints.clippy]
all = "warn"
